/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './Layout'
import { Route as pagesChatRouteImport } from './pages/Chat'
import { Route as pagesBenchmarkRouteImport } from './pages/Benchmark'
import { Route as pagesHomeRouteImport } from './pages/Home'

const pagesChatRoute = pagesChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesBenchmarkRoute = pagesBenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesHomeRoute = pagesHomeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof pagesHomeRoute
  '/benchmark': typeof pagesBenchmarkRoute
  '/chat': typeof pagesChatRoute
}
export interface FileRoutesByTo {
  '/': typeof pagesHomeRoute
  '/benchmark': typeof pagesBenchmarkRoute
  '/chat': typeof pagesChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof pagesHomeRoute
  '/benchmark': typeof pagesBenchmarkRoute
  '/chat': typeof pagesChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/benchmark' | '/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benchmark' | '/chat'
  id: '__root__' | '/' | '/benchmark' | '/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  pagesHomeRoute: typeof pagesHomeRoute
  pagesBenchmarkRoute: typeof pagesBenchmarkRoute
  pagesChatRoute: typeof pagesChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof pagesChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof pagesBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pagesHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  pagesHomeRoute: pagesHomeRoute,
  pagesBenchmarkRoute: pagesBenchmarkRoute,
  pagesChatRoute: pagesChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
